# baseURL = "https://keptn.sh/"
languageCode = "en-us"
title = "keptn | Cloud-native application life-cycle orchestration"
theme = "hugo-serif-theme"
relativeUrls = false
enableEmoji = true

ignoreFiles = [
"^(.*/docs/0.7.x/*)$",
"^(.*/docs/0.6.0/*)$",
"^(.*/docs/0.5.0/*)$",
"^(.*/docs/0.4.0/*)$",
"^(.*/docs/0.3.0/*)$",
"^(.*/docs/0.2.2/*)$",
"^(.*/docs/0.2.1/*)$",
"^(.*/docs/0.2.0/*)$",
"^(.*/docs/0.1.3/*)$",
"^(.*/docs/0.1.2/*)$",
"^(.*/docs/0.1.1/*)$",
"^(.*/docs/0.1.0/*)$" ]

[params]
    google_analytics_id="UA-133584243-1"

[blackfriday]
	plainIDAnchors = true
    # See https://github.com/gohugoio/hugo/issues/2424
	hrefTargetBlank = false
    angledQuotes = false
    latexDashes = true
    extensions = [""]
